// <auto-generated />
using System;
using LUNA.Models.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Angle.Migrations
{
    [DbContext(typeof(ProjectDataContext))]
    [Migration("20200127161345_NewCompositeKey")]
    partial class NewCompositeKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Angle.Models.Models.Ivy.Article", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CategoryID");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<long?>("LocationID");

                    b.Property<long?>("ManufacturerID");

                    b.Property<string>("ManufacturerPartNumber");

                    b.Property<double>("Pricing");

                    b.Property<long>("Quantity");

                    b.Property<string>("Status");

                    b.Property<long?>("SupplierID");

                    b.Property<string>("SupplierPartNumber");

                    b.Property<DateTime>("Updated");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("Angle.Models.Models.Ivy.Category", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Angle.Models.Models.Ivy.Location", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Angle.Models.Models.Ivy.Manufacturer", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientNumber");

                    b.Property<string>("Name");

                    b.Property<string>("WebAddress");

                    b.HasKey("ID");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Angle.Models.Models.Ivy.ProjectArticle", b =>
                {
                    b.Property<long>("ProjectID");

                    b.Property<long>("ArticleID");

                    b.HasKey("ProjectID", "ArticleID");

                    b.HasIndex("ArticleID");

                    b.ToTable("ProjectArticles");
                });

            modelBuilder.Entity("Angle.Models.Models.Ivy.Supplier", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientNumber");

                    b.Property<string>("Name");

                    b.Property<string>("WebAddress");

                    b.HasKey("ID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("Angle.Models.Models.TypeChild", b =>
                {
                    b.Property<long>("TypeID");

                    b.Property<long>("ChildID");

                    b.Property<long>("Quantity");

                    b.HasKey("TypeID", "ChildID");

                    b.HasIndex("ChildID");

                    b.ToTable("TypeChild");
                });

            modelBuilder.Entity("Angle.Models.ViewModels.AccountViewModel.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("Function");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("LUNA.Models.Customer", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressBill");

                    b.Property<string>("AddressOffice");

                    b.Property<string>("CompanyName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("LUNA.Models.History", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BootStrapBadge");

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("History");
                });

            modelBuilder.Entity("LUNA.Models.Models.Attribute", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Attribute");
                });

            modelBuilder.Entity("LUNA.Models.Models.Feature", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("LUNA.Models.Models.PType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("PType");
                });

            modelBuilder.Entity("LUNA.Models.Models.Person", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CellPhoneNumber");

                    b.Property<long?>("CustomerID");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("InternNumber");

                    b.Property<string>("Language");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("LUNA.Models.Models.ProductAttribute", b =>
                {
                    b.Property<long>("ProductID");

                    b.Property<long>("AttributeID");

                    b.Property<string>("Value");

                    b.HasKey("ProductID", "AttributeID");

                    b.HasIndex("AttributeID");

                    b.ToTable("ProductAttribute");
                });

            modelBuilder.Entity("LUNA.Models.Models.ProductHistory", b =>
                {
                    b.Property<long>("ProductID");

                    b.Property<long>("HistoryID");

                    b.Property<string>("UserID");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Comment");

                    b.HasKey("ProductID", "HistoryID", "UserID", "Date");

                    b.HasIndex("HistoryID");

                    b.HasIndex("UserID");

                    b.ToTable("ProductHistory");
                });

            modelBuilder.Entity("LUNA.Models.Models.ProductType", b =>
                {
                    b.Property<long>("ProductID");

                    b.Property<long>("DeviceTypeID");

                    b.Property<string>("Name");

                    b.HasKey("ProductID", "DeviceTypeID");

                    b.HasIndex("DeviceTypeID");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("LUNA.Models.Models.ProjectModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CustomerID");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("LUNA.Models.Models.ProjectPerson", b =>
                {
                    b.Property<long>("ProjectID");

                    b.Property<long>("PersonID");

                    b.HasKey("ProjectID", "PersonID");

                    b.HasIndex("PersonID");

                    b.ToTable("ProjectPerson");
                });

            modelBuilder.Entity("LUNA.Models.Models.StockInformation", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.HasKey("ID");

                    b.ToTable("StockInformation");
                });

            modelBuilder.Entity("LUNA.Models.Models.TypeAttribute", b =>
                {
                    b.Property<long>("DeviceTypeID");

                    b.Property<long>("AttributeID");

                    b.Property<string>("Value");

                    b.HasKey("DeviceTypeID", "AttributeID");

                    b.HasIndex("AttributeID");

                    b.ToTable("TypeAttribute");
                });

            modelBuilder.Entity("LUNA.Models.Models.TypeFeature", b =>
                {
                    b.Property<long>("DeviceTypeID");

                    b.Property<long>("FeatureID");

                    b.HasKey("DeviceTypeID", "FeatureID");

                    b.HasIndex("FeatureID");

                    b.ToTable("TypeFeature");
                });

            modelBuilder.Entity("LUNA.Models.Product", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("CustomerID");

                    b.Property<string>("Description");

                    b.Property<long?>("DeviceTypeID");

                    b.Property<long?>("ParentID");

                    b.Property<long?>("ProjectID");

                    b.Property<string>("SerialNumber");

                    b.Property<long?>("StockInformationID");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ParentID");

                    b.HasIndex("ProjectID");

                    b.HasIndex("StockInformationID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Angle.Models.Models.Ivy.Article", b =>
                {
                    b.HasOne("Angle.Models.Models.Ivy.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Angle.Models.Models.Ivy.ProjectArticle", b =>
                {
                    b.HasOne("Angle.Models.Models.Ivy.Article", "Article")
                        .WithMany("ProjectArticles")
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LUNA.Models.Models.ProjectModel", "Project")
                        .WithMany("ProjectArticles")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Angle.Models.Models.TypeChild", b =>
                {
                    b.HasOne("LUNA.Models.Models.PType", "Child")
                        .WithMany()
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LUNA.Models.Models.PType", "Type")
                        .WithMany("Childs")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LUNA.Models.Models.Person", b =>
                {
                    b.HasOne("LUNA.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");
                });

            modelBuilder.Entity("LUNA.Models.Models.ProductAttribute", b =>
                {
                    b.HasOne("LUNA.Models.Models.Attribute", "Attribute")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LUNA.Models.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LUNA.Models.Models.ProductHistory", b =>
                {
                    b.HasOne("LUNA.Models.History", "History")
                        .WithMany("ProductHistories")
                        .HasForeignKey("HistoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LUNA.Models.Product", "Product")
                        .WithMany("ProductHistories")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Angle.Models.ViewModels.AccountViewModel.ApplicationUser", "User")
                        .WithMany("ProductHistories")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LUNA.Models.Models.ProductType", b =>
                {
                    b.HasOne("LUNA.Models.Models.PType", "DeviceType")
                        .WithMany("ProductTypes")
                        .HasForeignKey("DeviceTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LUNA.Models.Product", "Product")
                        .WithMany("ProductTypes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LUNA.Models.Models.ProjectModel", b =>
                {
                    b.HasOne("LUNA.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");
                });

            modelBuilder.Entity("LUNA.Models.Models.ProjectPerson", b =>
                {
                    b.HasOne("LUNA.Models.Models.Person", "Person")
                        .WithMany("ProjectPersons")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LUNA.Models.Models.ProjectModel", "Project")
                        .WithMany("ProjectPersons")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LUNA.Models.Models.TypeAttribute", b =>
                {
                    b.HasOne("LUNA.Models.Models.Attribute", "Attribute")
                        .WithMany("TypeAttributes")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LUNA.Models.Models.PType", "DeviceType")
                        .WithMany("TypeAttributes")
                        .HasForeignKey("DeviceTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LUNA.Models.Models.TypeFeature", b =>
                {
                    b.HasOne("LUNA.Models.Models.PType", "DeviceType")
                        .WithMany("TypeFeatures")
                        .HasForeignKey("DeviceTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LUNA.Models.Models.Feature", "Feature")
                        .WithMany("TypeFeature")
                        .HasForeignKey("FeatureID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LUNA.Models.Product", b =>
                {
                    b.HasOne("LUNA.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("LUNA.Models.Product", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LUNA.Models.Models.ProjectModel", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID");

                    b.HasOne("LUNA.Models.Models.StockInformation", "StockInformation")
                        .WithMany()
                        .HasForeignKey("StockInformationID");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Angle.Models.ViewModels.AccountViewModel.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Angle.Models.ViewModels.AccountViewModel.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Angle.Models.ViewModels.AccountViewModel.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Angle.Models.ViewModels.AccountViewModel.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
